name-template: '🚀 ncexs Toolkit v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

template: |
  ## 🧰 ncexs Toolkit – v$NEXT_PATCH_VERSION Refined Release

  $CHANGES

  ---

  {% include .github/release-notes/v$NEXT_PATCH_VERSION.md %}

categories:
  - title: '✨ Features & Enhancements'
    labels:
      - 'feat'
      - 'feature'
      - 'enhancement'
  - title: '🔧 Bug Fixes & Refactors'
    labels:
      - 'fix'
      - 'bug'
      - 'refactor'
  - title: '⚡ Performance'
    labels:
      - 'perf'
      - 'performance'
  - title: '📄 Documentation'
    labels:
      - 'docs'
      - 'documentation'
